### ISSUE TITLE
Add Code Of Conduct

### ISSUE THREAD

**Issue by jukecraft** [codefreezefi/codefreeze.fi#143]
It's a good thing to do and softwarecrafters.org would require it soon https://github.com/softwarecrafters/website/pull/72

**Comment by jukecraft** [comment]
First draft:
---
All attendees of codefreeze are required to agree with the following code of conduct (CoC).

# Code of Conduct

Codefreeze isn't an officially organised event.
For enforcement of this code of conduct, we only have official authority of the private accommodation we are using for sessions and the activities we organise.
With everything else, we will try to work on enforcement with the Suomen Latu staff and local authorities.
This is still a public space used by non-participants as well, please don't assume that everyone has read or will follow this code of conduct.

## Inclusiveness
A goal of Codefreeze is to be inclusive and welcoming to attendees with the most varied and diverse backgrounds possible.
Please read our full code of conduct before booking, discussing online and before coming to codefreeze. But please don’t feel intimidated by it—these are simple rules, and they will make life better for everyone at codefreeze.

## Why we have a CoC
We are dedicated to create an event where everybody can learn, teach, share, network and have a good time. This can only work if we are inclusive to the largest number of contributors, and if we create an environment, where everybody feels safe and welcome.
Yes, we value discussion and disagreement. And discussion can become heated. But there have to be rules, and there has to be a red line.
In this code of conduct, we lay out those rules and red lines.

## Safe Environment
We are committed to providing a friendly, safe and welcoming environment for all, regardless of gender, sexual orientation, age, field of expertise, ability, ethnicity, socioeconomic status, and religion (or lack thereof).
And so we invite all those who participate in codefreeze, and the community surrounding the event, to help us create safe and positive experiences for everyone. With your help, this event can be a great experience for everyone!
Treat everyone professionally. Everybody at the conference is a professional in their field. Treat all attendees as equals. Ask before you teach. Do not explain things without being asked.
Be welcoming, friendly, and patient. Give people the benefit of the doubt. Ask questions before jumping to conclusions.
Be respectful. Not all of us will agree with each other all the time, but disagreement is no excuse for poor behaviour and poor manners. We might all experience some frustration now and then, but we cannot allow that frustration to turn into a personal attack.
Be aware of the effect your words may have on others. We are a community of professionals, and we conduct ourselves professionally. Be kind to others. Do not insult or put down other participants. Harassment and other exclusionary behavior aren't acceptable.
Be careful with jokes. We do not tolerate any CoC violations, even if “it was just a joke”.
Admit when you do not know something. Encourage others to admit when they do not know something—and never joke about it. We are all here to learn.
There might be people taking photographs. If you don't want to be photographed let them know. If you want to publish a photo, ask the people in the photograph first.
If you're involved in outdoor activities, look after each other and be mindful that not everyone has the same ability. Please respect nature and the instructions from the official guides.

## CoC Violations
If you think someone has violated our code of conduct—even if you were not directly involved, like you just overheard a conversation—please:
Let the person know that what they did is not appropriate and ask them to stop if you feel able to do so
Contact the volunteers of codefreeze (See contact details below). We will discuss any possible action with you first.
But please give people the benefit of doubt. If there is even a slight chance that this was a misunderstanding (e.g. the person did not speak in their native language, and did not find the right words), try to sort it out in a friendly, constructive way.
When we learn about a CoC violations, volunteers will hear both sides, and then take action we deem appropriate, such as:
- Give a warning
- Have a longer talk about our values
- we are going to ask the staff to expel the person, though we don't authority to do so ourselves, see above
- exclude the person from our privately used accommodation & activities we organise
- Call the authorities
- inform organisers of other events

## Unacceptable Behaviour
Unacceptable behaviour includes, but is not limited to:
- Harassment, and other exclusionary behaviour. Deliberate intimidation and threats.
- Aggressive or sexualized language and content. Unwanted sexual advances.
- Insulting or putting down other participants.
- Publishing or telling others, that a participant belongs to a particular identity group without asking their consent first, e.g outing someone.
- “Well-actuallies”: Telling people what they “actually meant to say”.
- Other conduct which could reasonably be considered inappropriate in a professional setting.
To clarify, although this doesn't take away from the other rules, it is ok to be naked in private saunas and changing rooms, but not mandatory. If you are unsure about what is appropriate or if you're uncomfortable about this, please talk to a volunteer listed below.

## Need Help?
If you need help, have any further questions or have any other concerns, please contact a volunteer immediately.
- Find and talk to the volunteers at the conference
- Contact [email]
- Ask in the channel #codefreeze on Slack
- Contact a volunteer on Slack
This code of conduct applies to the event itself, and to all digital spaces that are related to the event, such as GitHub, Slack and Trello.

## Credits
These values are inspired by SoCraTes Germany https://socrates-conference.de/values.

## Further Questions?
Feel invited to contact us via our details listed below

Signed,
The volunteers
[add volunteer details]

**Comment by coderbyheart** [comment]
Formatted with Markdown for improved readability

**Comment by coderbyheart** [comment]
PR: https://github.com/rinkkasatiainen/codefreeze.fi/pull/153
