### ISSUE TITLE
Pictures are broken

### ISSUE THREAD

**Issue by coderbyheart** [codefreezefi/codefreeze.fi#193]
![image](https://user-images.githubusercontent.com/188915/82815400-66329f80-9e99-11ea-84aa-acad09f8b959.png)

Probably Twitter URLs have changed.

**Comment by ridingwolf** [comment]
Must be something different as mine does not direct to twitter

**Comment by ridingwolf** [comment]
Which image urls are resolved seems a bit flacky. 5 minutes ago only Aki and my (Wouter) got resolved, now only 2 seem to give problems
![image](https://user-images.githubusercontent.com/1907168/82834567-d6edb200-9ec1-11ea-983d-15972bb23577.png)

**Comment by coderbyheart** [comment]
Works in the latest version.
