### ISSUE TITLE
Registration for andibraeu

### ISSUE THREAD

**Issue by andibraeu** [codefreezefi/codefreeze.fi#199]
This issue has been created automatically on behalf of andibraeu

```json
{"name":"andibraeu","pronouns":"he","image":"https://ja.ishalt.so/andibraeu.jpg","twitter":"https://twitter.com/evaltenberga","linkedin":"https://www.linkedin.com/in/andreasbraeu/","link":"https://blog.andi95.de"}
```

**Comment by coderbyheart** [comment]
We need to change the script to create Markdown files: https://github.com/codefreezefi/codefreeze.fi/blob/gh-pages/_participants/_template.md

**Comment by andibraeu** [comment]
what exactly do you mean?

The file in https://github.com/codefreezefi/codefreeze.fi/pull/200/files looks ok to me

**Comment by coderbyheart** [comment]
Oh, I totally forgot how we made it work.
