### ISSUE TITLE
Registration for Prachi Nawathe

### ISSUE THREAD

**Issue by codefreeze-registrations** [codefreezefi/codefreeze.fi#259]
This issue has been created automatically on behalf of Prachi Nawathe

```json
{"name":"Prachi Nawathe","pronouns":"she","image":"https://drive.google.com/file/d/1BuJgPms0iFVid4ek27XYrrDHMIMk9fgB/view?usp=share_link"}
```

**Comment by coderbyheart** [comment]
![image](https://user-images.githubusercontent.com/188915/203660680-ed72a87b-3efc-44d3-a750-7ca45e9ecf39.png)
