### ISSUE TITLE
The date of the event is not visible on www.codefreeze.fi

### ISSUE THREAD

**Issue by luontola** [codefreezefi/codefreeze.fi#79]
The date of this year's event reads in https://github.com/rinkkasatiainen/codefreeze.fi/blob/2954cd4d46599c954c571170b378454e81e77882/_layouts/index.html but it's not visible anywhere on http://www.codefreeze.fi/

Is Jan 16th - Jan 18th, 2017 still correct?

**Comment by rinkkasatiainen** [comment]
Hi,
Yes. I'm leaving to Lapland myself today. The dates are those - and there are people arriving on Sat/Sun.

I'll update the information to web site soon.
